using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace SimplestGitSourceGenerator;

[Generator]
public class GitInfoGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var gitInfo = context.AnalyzerConfigOptionsProvider
            .Select((options, _) =>
            {
                options.GlobalOptions.TryGetValue("build_property.GitHash", out var hash);
                options.GlobalOptions.TryGetValue("build_property.GitBranch", out var branch);
                options.GlobalOptions.TryGetValue("build_property.GitCommitDate", out var commitDate);
                options.GlobalOptions.TryGetValue("build_property.GitTag", out var tag);
                options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);

                return new GitInfo
                {
                    Namespace = ns,
                    CommitHash = hash,
                    Branch = branch,
                    CommitDate = commitDate,
                    Tag = tag
                };
            });

        context.RegisterSourceOutput(gitInfo, (spc, info) =>
        {
            var source = $@"// <auto-generated/>
namespace {info.Namespace ?? "GitInfo"};

public static class SimplestGit
{{
    public const string CommitHash = ""{info.CommitHash}"";
    public const string Branch = ""{info.Branch}"";
    public const string CommitDate = ""{info.CommitDate}"";
    public const string Tag = ""{info.Tag}"";
}}";
            spc.AddSource("GitInfo", source);
        });
    }

    private sealed class GitInfo
    {
        public string? Namespace { get; set; }
        public string? CommitHash { get; set; }
        public string? Branch { get; set; }
        public string? CommitDate { get; set; }
        public string? Tag { get; set; }
    }
}