using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace SimplestGitSourceGenerator;

[Generator]
public class GitInfoGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var gitInfo = context.AnalyzerConfigOptionsProvider
            .Select((options, _) =>
            {
                options.GlobalOptions.TryGetValue("build_property.SimplestGitCommitHash", out var hash);
                options.GlobalOptions.TryGetValue("build_property.SimplestGitBranch", out var branch);
                options.GlobalOptions.TryGetValue("build_property.SimplestGitCommitDate", out var commitDate);
                options.GlobalOptions.TryGetValue("build_property.SimplestGitTag", out var tag);
                options.GlobalOptions.TryGetValue("build_property.SimplestGitRemoteUrl", out var remoteUrl);

                return new GitInfo
                {
                    CommitHash = hash,
                    Branch = branch,
                    CommitDate = commitDate,
                    Tag = tag,
                    RemoteUrl = remoteUrl
                };
            });

        context.RegisterSourceOutput(gitInfo, (spc, info) =>
        {
            var source = $@"// <auto-generated/>
namespace SimplestGitSourceGenerator;

internal static class SimplestGit
{{
    public const string CommitHash = {EscapeStringLiteral(info.CommitHash)};
    public const string Branch = {EscapeStringLiteral(info.Branch)};
    public const string CommitDate = {EscapeStringLiteral(info.CommitDate)};
    public const string Tag = {EscapeStringLiteral(info.Tag)};
    public const string RemoteUrl = {EscapeStringLiteral(info.RemoteUrl)};
}}";
            spc.AddSource("GitInfo", source);
        });
    }

    private static string EscapeStringLiteral(string? value)
    {
        if (value is null)
        {
            return "\"\"";
        }

        return SymbolDisplay.FormatLiteral(value, quote: true);
    }

    private sealed class GitInfo
    {
        public string? CommitHash { get; set; }
        public string? Branch { get; set; }
        public string? CommitDate { get; set; }
        public string? Tag { get; set; }
        public string? RemoteUrl { get; set; }
    }
}